/// Z3 Bindings for Zig
/// Targets Z3 version 4.15.2
///
/// the initial version of this file was generated by claude sonnet 4.16
const std = @import("std");

// ============================================================
// Raw C FFI declarations
// ============================================================

pub const z3 = struct {
    // ----- Opaque pointer types -----
    pub const Z3_config = opaque {};
    pub const Z3_context = opaque {};
    pub const Z3_symbol = opaque {};
    pub const Z3_ast = opaque {};
    pub const Z3_sort = opaque {};
    pub const Z3_func_decl = opaque {};
    pub const Z3_app = opaque {};
    pub const Z3_pattern = opaque {};
    pub const Z3_model = opaque {};
    pub const Z3_literals = opaque {};
    pub const Z3_constructor = opaque {};
    pub const Z3_constructor_list = opaque {};
    pub const Z3_solver = opaque {};
    pub const Z3_goal = opaque {};
    pub const Z3_tactic = opaque {};
    pub const Z3_probe = opaque {};
    pub const Z3_stats = opaque {};
    pub const Z3_ast_vector = opaque {};
    pub const Z3_ast_map = opaque {};
    pub const Z3_apply_result = opaque {};
    pub const Z3_func_interp = opaque {};
    pub const Z3_func_entry = opaque {};
    pub const Z3_fixedpoint = opaque {};
    pub const Z3_optimize = opaque {};
    pub const Z3_param_descrs = opaque {};
    pub const Z3_params = opaque {};
    pub const Z3_rcf_num = opaque {};
    pub const Z3_parser_context = opaque {};

    // ----- Enumerations -----

    pub const Z3_lbool = enum(c_int) {
        L_FALSE = -1,
        L_UNDEF = 0,
        L_TRUE = 1,
    };

    pub const Z3_symbol_kind = enum(c_uint) {
        INT_SYMBOL = 0,
        STRING_SYMBOL = 1,
    };

    pub const Z3_parameter_kind = enum(c_uint) {
        PARAMETER_INT = 0,
        PARAMETER_DOUBLE = 1,
        PARAMETER_RATIONAL = 2,
        PARAMETER_SYMBOL = 3,
        PARAMETER_SORT = 4,
        PARAMETER_AST = 5,
        PARAMETER_FUNC_DECL = 6,
    };

    pub const Z3_sort_kind = enum(c_uint) {
        UNINTERPRETED_SORT = 0,
        BOOL_SORT = 1,
        INT_SORT = 2,
        REAL_SORT = 3,
        BV_SORT = 4,
        ARRAY_SORT = 5,
        DATATYPE_SORT = 6,
        RELATION_SORT = 7,
        FINITE_DOMAIN_SORT = 8,
        FLOATING_POINT_SORT = 9,
        ROUNDING_MODE_SORT = 10,
        SEQ_SORT = 11,
        RE_SORT = 12,
        CHAR_SORT = 13,
        UNKNOWN_SORT = 1000,
    };

    pub const Z3_ast_kind = enum(c_uint) {
        NUMERAL_AST = 0,
        APP_AST = 1,
        VAR_AST = 2,
        QUANTIFIER_AST = 3,
        SORT_AST = 4,
        FUNC_DECL_AST = 5,
        UNKNOWN_AST = 1000,
    };

    pub const Z3_decl_kind = enum(c_uint) {
        OP_TRUE = 256,
        OP_FALSE = 257,
        OP_EQ = 258,
        OP_DISTINCT = 259,
        OP_ITE = 260,
        OP_AND = 261,
        OP_OR = 262,
        OP_IFF = 263,
        OP_XOR = 264,
        OP_NOT = 265,
        OP_IMPLIES = 266,
        OP_OEQ = 267,
        OP_INTERP = 268,
        // Arithmetic
        OP_ANUM = 512,
        OP_AGNUM = 513,
        OP_LE = 514,
        OP_GE = 515,
        OP_LT = 516,
        OP_GT = 517,
        OP_ADD = 518,
        OP_SUB = 519,
        OP_UMINUS = 520,
        OP_MUL = 521,
        OP_DIV = 522,
        OP_IDIV = 523,
        OP_REM = 524,
        OP_MOD = 525,
        OP_TO_REAL = 526,
        OP_TO_INT = 527,
        OP_IS_INT = 528,
        OP_POWER = 529,
        // Bit-vectors
        OP_BNUM = 1024,
        OP_BIT1 = 1025,
        OP_BIT0 = 1026,
        OP_BNEG = 1027,
        OP_BADD = 1028,
        OP_BSUB = 1029,
        OP_BMUL = 1030,
        OP_BSDIV = 1031,
        OP_BUDIV = 1032,
        OP_BSREM = 1033,
        OP_BUREM = 1034,
        OP_BSMOD = 1035,
        OP_BSDIV0 = 1036,
        OP_BUDIV0 = 1037,
        OP_BSREM0 = 1038,
        OP_BUREM0 = 1039,
        OP_BSMOD0 = 1040,
        OP_ULEQ = 1041,
        OP_SLEQ = 1042,
        OP_UGEQ = 1043,
        OP_SGEQ = 1044,
        OP_ULT = 1045,
        OP_SLT = 1046,
        OP_UGT = 1047,
        OP_SGT = 1048,
        OP_BAND = 1049,
        OP_BOR = 1050,
        OP_BNOT = 1051,
        OP_BXOR = 1052,
        OP_BNAND = 1053,
        OP_BNOR = 1054,
        OP_BXNOR = 1055,
        OP_CONCAT = 1056,
        OP_SIGN_EXT = 1057,
        OP_ZERO_EXT = 1058,
        OP_EXTRACT = 1059,
        OP_REPEAT = 1060,
        OP_BREDOR = 1061,
        OP_BREDAND = 1062,
        OP_BCOMP = 1063,
        OP_BSHL = 1064,
        OP_BLSHR = 1065,
        OP_BASHR = 1066,
        OP_ROTATE_LEFT = 1067,
        OP_ROTATE_RIGHT = 1068,
        OP_EXT_ROTATE_LEFT = 1069,
        OP_EXT_ROTATE_RIGHT = 1070,
        OP_INT2BV = 1071,
        OP_BV2INT = 1072,
        OP_CARRY = 1073,
        OP_XOR3 = 1074,
        OP_BSMUL_NO_OVFL = 1075,
        OP_BUMUL_NO_OVFL = 1076,
        OP_BSMUL_NO_UDFL = 1077,
        OP_BSDIV_I = 1078,
        OP_BUDIV_I = 1079,
        OP_BSREM_I = 1080,
        OP_BUREM_I = 1081,
        OP_BSMOD_I = 1082,
        // Arrays
        OP_SELECT = 1536,
        OP_STORE = 1537,
        OP_CONST_ARRAY = 1538,
        OP_ARRAY_MAP = 1539,
        OP_ARRAY_DEFAULT = 1540,
        OP_SET_UNION = 1541,
        OP_SET_INTERSECT = 1542,
        OP_SET_DIFFERENCE = 1543,
        OP_SET_COMPLEMENT = 1544,
        OP_SET_SUBSET = 1545,
        OP_AS_ARRAY = 1546,
        OP_ARRAY_EXT = 1547,
        OP_SET_HAS_SIZE = 1548,
        OP_SET_CARD = 1549,
        // Sequences / strings
        OP_SEQ_UNIT = 1792,
        OP_SEQ_EMPTY = 1793,
        OP_SEQ_CONCAT = 1794,
        OP_SEQ_PREFIX = 1795,
        OP_SEQ_SUFFIX = 1796,
        OP_SEQ_CONTAINS = 1797,
        OP_SEQ_EXTRACT = 1798,
        OP_SEQ_REPLACE = 1799,
        OP_SEQ_REPLACE_RE = 1800,
        OP_SEQ_REPLACE_RE_ALL = 1801,
        OP_SEQ_REPLACE_ALL = 1802,
        OP_SEQ_AT = 1803,
        OP_SEQ_NTH = 1804,
        OP_SEQ_LENGTH = 1805,
        OP_SEQ_INDEX = 1806,
        OP_SEQ_LAST_INDEX = 1807,
        OP_SEQ_TO_RE = 1808,
        OP_SEQ_IN_RE = 1809,
        OP_STR_TO_INT = 1810,
        OP_INT_TO_STR = 1811,
        OP_UBV_TO_STR = 1812,
        OP_SBV_TO_STR = 1813,
        OP_STR_TO_CODE = 1814,
        OP_STR_FROM_CODE = 1815,
        OP_STRING_LT = 1816,
        OP_STRING_LE = 1817,
        OP_RE_PLUS = 1818,
        OP_RE_STAR = 1819,
        OP_RE_OPTION = 1820,
        OP_RE_CONCAT = 1821,
        OP_RE_UNION = 1822,
        OP_RE_RANGE = 1823,
        OP_RE_DIFF = 1824,
        OP_RE_INTERSECT = 1825,
        OP_RE_LOOP = 1826,
        OP_RE_POWER = 1827,
        OP_RE_COMPLEMENT = 1828,
        OP_RE_EMPTY_SET = 1829,
        OP_RE_FULL_SET = 1830,
        OP_RE_FULL_CHAR_SET = 1831,
        OP_RE_OF_PRED = 1832,
        OP_RE_REVERSE = 1833,
        OP_RE_DERIVATIVE = 1834,
        OP_CHAR_CONST = 1835,
        OP_CHAR_LE = 1836,
        OP_CHAR_TO_INT = 1837,
        OP_CHAR_TO_BV = 1838,
        OP_CHAR_FROM_BV = 1839,
        OP_CHAR_IS_DIGIT = 1840,
        // Floating point
        OP_FPA_RM_NEAREST_TIES_TO_EVEN = 2048,
        OP_FPA_RM_NEAREST_TIES_TO_AWAY = 2049,
        OP_FPA_RM_TOWARD_POSITIVE = 2050,
        OP_FPA_RM_TOWARD_NEGATIVE = 2051,
        OP_FPA_RM_TOWARD_ZERO = 2052,
        OP_FPA_NUM = 2053,
        OP_FPA_PLUS_INF = 2054,
        OP_FPA_MINUS_INF = 2055,
        OP_FPA_NAN = 2056,
        OP_FPA_PLUS_ZERO = 2057,
        OP_FPA_MINUS_ZERO = 2058,
        OP_FPA_ADD = 2059,
        OP_FPA_SUB = 2060,
        OP_FPA_NEG = 2061,
        OP_FPA_MUL = 2062,
        OP_FPA_DIV = 2063,
        OP_FPA_REM = 2064,
        OP_FPA_ABS = 2065,
        OP_FPA_MIN = 2066,
        OP_FPA_MAX = 2067,
        OP_FPA_FMA = 2068,
        OP_FPA_SQRT = 2069,
        OP_FPA_ROUND_TO_INTEGRAL = 2070,
        OP_FPA_EQ = 2071,
        OP_FPA_LT = 2072,
        OP_FPA_GT = 2073,
        OP_FPA_LE = 2074,
        OP_FPA_GE = 2075,
        OP_FPA_IS_NAN = 2076,
        OP_FPA_IS_INF = 2077,
        OP_FPA_IS_ZERO = 2078,
        OP_FPA_IS_NORMAL = 2079,
        OP_FPA_IS_SUBNORMAL = 2080,
        OP_FPA_IS_NEGATIVE = 2081,
        OP_FPA_IS_POSITIVE = 2082,
        OP_FPA_FP = 2083,
        OP_FPA_TO_FP = 2084,
        OP_FPA_TO_FP_UNSIGNED = 2085,
        OP_FPA_TO_UBV = 2086,
        OP_FPA_TO_SBV = 2087,
        OP_FPA_TO_REAL = 2088,
        OP_FPA_TO_IEEE_BV = 2089,
        OP_FPA_BVWRAP = 2090,
        OP_FPA_BV2RM = 2091,
        OP_INTERNAL = 2092,
        OP_RECURSIVE = 2093,
        OP_UNINTERPRETED = 2094,
    };

    pub const Z3_error_code = enum(c_uint) {
        OK = 0,
        SORT_ERROR = 1,
        IOB = 2,
        INVALID_ARG = 3,
        PARSER_ERROR = 4,
        NO_PARSER = 5,
        INVALID_PATTERN = 6,
        MEMOUT_FAIL = 7,
        FILE_ACCESS_ERROR = 8,
        INTERNAL_FATAL = 9,
        INVALID_USAGE = 10,
        DEC_REF_ERROR = 11,
        EXCEPTION = 12,
    };

    pub const Z3_goal_prec = enum(c_uint) {
        GOAL_PRECISE = 0,
        GOAL_UNDER = 1,
        GOAL_OVER = 2,
        GOAL_UNDER_OVER = 3,
    };

    // ----- Error handler callback -----
    pub const Z3_error_handler = ?*const fn (?*Z3_context, Z3_error_code) callconv(.C) void;

    // =========================================================
    // Configuration & Context
    // =========================================================
    pub extern fn Z3_mk_config() ?*Z3_config;
    pub extern fn Z3_del_config(c: ?*Z3_config) void;
    pub extern fn Z3_set_param_value(c: ?*Z3_config, param_id: [*:0]const u8, param_value: [*:0]const u8) void;

    pub extern fn Z3_mk_context(c: ?*Z3_config) ?*Z3_context;
    pub extern fn Z3_mk_context_rc(c: ?*Z3_config) ?*Z3_context;
    pub extern fn Z3_del_context(c: ?*Z3_context) void;
    pub extern fn Z3_inc_ref(c: ?*Z3_context, a: ?*Z3_ast) void;
    pub extern fn Z3_dec_ref(c: ?*Z3_context, a: ?*Z3_ast) void;
    pub extern fn Z3_update_param_value(c: ?*Z3_context, param_id: [*:0]const u8, param_value: [*:0]const u8) void;
    pub extern fn Z3_interrupt(c: ?*Z3_context) void;

    // =========================================================
    // Parameters
    // =========================================================
    pub extern fn Z3_mk_params(c: ?*Z3_context) ?*Z3_params;
    pub extern fn Z3_params_inc_ref(c: ?*Z3_context, p: ?*Z3_params) void;
    pub extern fn Z3_params_dec_ref(c: ?*Z3_context, p: ?*Z3_params) void;
    pub extern fn Z3_params_set_bool(c: ?*Z3_context, p: ?*Z3_params, k: ?*Z3_symbol, v: bool) void;
    pub extern fn Z3_params_set_uint(c: ?*Z3_context, p: ?*Z3_params, k: ?*Z3_symbol, v: c_uint) void;
    pub extern fn Z3_params_set_double(c: ?*Z3_context, p: ?*Z3_params, k: ?*Z3_symbol, v: f64) void;
    pub extern fn Z3_params_set_symbol(c: ?*Z3_context, p: ?*Z3_params, k: ?*Z3_symbol, v: ?*Z3_symbol) void;
    pub extern fn Z3_params_to_string(c: ?*Z3_context, p: ?*Z3_params) ?[*:0]const u8;
    pub extern fn Z3_params_validate(c: ?*Z3_context, p: ?*Z3_params, d: ?*Z3_param_descrs) void;

    // =========================================================
    // Symbols
    // =========================================================
    pub extern fn Z3_mk_int_symbol(c: ?*Z3_context, i: c_int) ?*Z3_symbol;
    pub extern fn Z3_mk_string_symbol(c: ?*Z3_context, s: [*:0]const u8) ?*Z3_symbol;
    pub extern fn Z3_get_symbol_kind(c: ?*Z3_context, s: ?*Z3_symbol) Z3_symbol_kind;
    pub extern fn Z3_get_symbol_int(c: ?*Z3_context, s: ?*Z3_symbol) c_int;
    pub extern fn Z3_get_symbol_string(c: ?*Z3_context, s: ?*Z3_symbol) ?[*:0]const u8;

    // =========================================================
    // Sorts
    // =========================================================
    pub extern fn Z3_mk_uninterpreted_sort(c: ?*Z3_context, s: ?*Z3_symbol) ?*Z3_sort;
    pub extern fn Z3_mk_bool_sort(c: ?*Z3_context) ?*Z3_sort;
    pub extern fn Z3_mk_int_sort(c: ?*Z3_context) ?*Z3_sort;
    pub extern fn Z3_mk_real_sort(c: ?*Z3_context) ?*Z3_sort;
    pub extern fn Z3_mk_bv_sort(c: ?*Z3_context, sz: c_uint) ?*Z3_sort;
    pub extern fn Z3_mk_finite_domain_sort(c: ?*Z3_context, name: ?*Z3_symbol, size: u64) ?*Z3_sort;
    pub extern fn Z3_mk_array_sort(c: ?*Z3_context, domain: ?*Z3_sort, range: ?*Z3_sort) ?*Z3_sort;
    pub extern fn Z3_mk_array_sort_n(c: ?*Z3_context, n: c_uint, domain: [*]const ?*Z3_sort, range: ?*Z3_sort) ?*Z3_sort;
    pub extern fn Z3_mk_tuple_sort(c: ?*Z3_context, mk_tuple_name: ?*Z3_symbol, num_fields: c_uint, field_names: [*]const ?*Z3_symbol, field_sorts: [*]const ?*Z3_sort, mk_tuple_decl: *?*Z3_func_decl, proj_decl: [*]?*Z3_func_decl) ?*Z3_sort;
    pub extern fn Z3_mk_enumeration_sort(c: ?*Z3_context, name: ?*Z3_symbol, n: c_uint, enum_names: [*]const ?*Z3_symbol, enum_consts: [*]?*Z3_func_decl, enum_testers: [*]?*Z3_func_decl) ?*Z3_sort;
    pub extern fn Z3_mk_list_sort(c: ?*Z3_context, name: ?*Z3_symbol, elem_sort: ?*Z3_sort, nil_decl: *?*Z3_func_decl, is_nil_decl: *?*Z3_func_decl, cons_decl: *?*Z3_func_decl, is_cons_decl: *?*Z3_func_decl, head_decl: *?*Z3_func_decl, tail_decl: *?*Z3_func_decl) ?*Z3_sort;
    pub extern fn Z3_mk_set_sort(c: ?*Z3_context, ty: ?*Z3_sort) ?*Z3_sort;
    pub extern fn Z3_mk_string_sort(c: ?*Z3_context) ?*Z3_sort;
    pub extern fn Z3_mk_char_sort(c: ?*Z3_context) ?*Z3_sort;
    pub extern fn Z3_mk_re_sort(c: ?*Z3_context, seq: ?*Z3_sort) ?*Z3_sort;
    pub extern fn Z3_mk_seq_sort(c: ?*Z3_context, s: ?*Z3_sort) ?*Z3_sort;
    pub extern fn Z3_is_seq_sort(c: ?*Z3_context, s: ?*Z3_sort) bool;
    pub extern fn Z3_is_re_sort(c: ?*Z3_context, s: ?*Z3_sort) bool;
    pub extern fn Z3_is_string_sort(c: ?*Z3_context, s: ?*Z3_sort) bool;
    pub extern fn Z3_is_char_sort(c: ?*Z3_context, s: ?*Z3_sort) bool;
    pub extern fn Z3_get_seq_sort_basis(c: ?*Z3_context, s: ?*Z3_sort) ?*Z3_sort;
    pub extern fn Z3_get_re_sort_basis(c: ?*Z3_context, s: ?*Z3_sort) ?*Z3_sort;
    pub extern fn Z3_get_sort_kind(c: ?*Z3_context, t: ?*Z3_sort) Z3_sort_kind;
    pub extern fn Z3_get_bv_sort_size(c: ?*Z3_context, t: ?*Z3_sort) c_uint;
    pub extern fn Z3_get_finite_domain_sort_size(c: ?*Z3_context, s: ?*Z3_sort, r: *u64) bool;
    pub extern fn Z3_get_array_sort_domain(c: ?*Z3_context, t: ?*Z3_sort) ?*Z3_sort;
    pub extern fn Z3_get_array_sort_domain_n(c: ?*Z3_context, t: ?*Z3_sort, idx: c_uint) ?*Z3_sort;
    pub extern fn Z3_get_array_sort_range(c: ?*Z3_context, t: ?*Z3_sort) ?*Z3_sort;
    pub extern fn Z3_get_tuple_sort_mk_decl(c: ?*Z3_context, t: ?*Z3_sort) ?*Z3_func_decl;
    pub extern fn Z3_get_tuple_sort_num_fields(c: ?*Z3_context, t: ?*Z3_sort) c_uint;
    pub extern fn Z3_get_tuple_sort_field_decl(c: ?*Z3_context, t: ?*Z3_sort, i: c_uint) ?*Z3_func_decl;
    pub extern fn Z3_get_datatype_sort_num_constructors(c: ?*Z3_context, t: ?*Z3_sort) c_uint;
    pub extern fn Z3_get_datatype_sort_constructor(c: ?*Z3_context, t: ?*Z3_sort, idx: c_uint) ?*Z3_func_decl;
    pub extern fn Z3_get_datatype_sort_recognizer(c: ?*Z3_context, t: ?*Z3_sort, idx: c_uint) ?*Z3_func_decl;
    pub extern fn Z3_get_datatype_sort_constructor_accessor(c: ?*Z3_context, t: ?*Z3_sort, idx_c: c_uint, idx_a: c_uint) ?*Z3_func_decl;
    pub extern fn Z3_datatype_update_field(c: ?*Z3_context, field_access: ?*Z3_func_decl, t: ?*Z3_ast, value: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_get_relation_arity(c: ?*Z3_context, s: ?*Z3_sort) c_uint;
    pub extern fn Z3_get_relation_column(c: ?*Z3_context, s: ?*Z3_sort, col: c_uint) ?*Z3_sort;

    // =========================================================
    // Constants / Function declarations
    // =========================================================
    pub extern fn Z3_mk_func_decl(c: ?*Z3_context, s: ?*Z3_symbol, domain_size: c_uint, domain: [*]const ?*Z3_sort, range: ?*Z3_sort) ?*Z3_func_decl;
    pub extern fn Z3_mk_app(c: ?*Z3_context, d: ?*Z3_func_decl, num_args: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_const(c: ?*Z3_context, s: ?*Z3_symbol, ty: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_mk_fresh_func_decl(c: ?*Z3_context, prefix: ?[*:0]const u8, domain_size: c_uint, domain: [*]const ?*Z3_sort, range: ?*Z3_sort) ?*Z3_func_decl;
    pub extern fn Z3_mk_fresh_const(c: ?*Z3_context, prefix: ?[*:0]const u8, ty: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_mk_rec_func_decl(c: ?*Z3_context, s: ?*Z3_symbol, domain_size: c_uint, domain: [*]const ?*Z3_sort, range: ?*Z3_sort) ?*Z3_func_decl;
    pub extern fn Z3_add_rec_def(c: ?*Z3_context, f: ?*Z3_func_decl, n: c_uint, args: [*]?*Z3_ast, body: ?*Z3_ast) void;

    // =========================================================
    // Propositional / Boolean
    // =========================================================
    pub extern fn Z3_mk_true(c: ?*Z3_context) ?*Z3_ast;
    pub extern fn Z3_mk_false(c: ?*Z3_context) ?*Z3_ast;
    pub extern fn Z3_mk_eq(c: ?*Z3_context, l: ?*Z3_ast, r: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_distinct(c: ?*Z3_context, num_args: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_not(c: ?*Z3_context, a: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_ite(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast, t3: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_iff(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_implies(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_xor(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_and(c: ?*Z3_context, num_args: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_or(c: ?*Z3_context, num_args: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;

    // =========================================================
    // Arithmetic
    // =========================================================
    pub extern fn Z3_mk_add(c: ?*Z3_context, num_args: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_mul(c: ?*Z3_context, num_args: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_sub(c: ?*Z3_context, num_args: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_unary_minus(c: ?*Z3_context, arg: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_div(c: ?*Z3_context, arg1: ?*Z3_ast, arg2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_mod(c: ?*Z3_context, arg1: ?*Z3_ast, arg2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_rem(c: ?*Z3_context, arg1: ?*Z3_ast, arg2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_power(c: ?*Z3_context, arg1: ?*Z3_ast, arg2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_lt(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_le(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_gt(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_ge(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_divides(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_int2real(c: ?*Z3_context, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_real2int(c: ?*Z3_context, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_is_int(c: ?*Z3_context, t1: ?*Z3_ast) ?*Z3_ast;

    // =========================================================
    // Bit-vectors
    // =========================================================
    pub extern fn Z3_mk_bvnot(c: ?*Z3_context, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvredand(c: ?*Z3_context, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvredor(c: ?*Z3_context, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvand(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvor(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvxor(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvnand(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvnor(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvxnor(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvneg(c: ?*Z3_context, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvadd(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvsub(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvmul(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvudiv(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvsdiv(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvurem(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvsrem(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvsmod(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvult(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvslt(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvule(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvsle(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvuge(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvsge(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvugt(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvsgt(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_concat(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_extract(c: ?*Z3_context, high: c_uint, low: c_uint, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_sign_ext(c: ?*Z3_context, i: c_uint, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_zero_ext(c: ?*Z3_context, i: c_uint, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_repeat(c: ?*Z3_context, i: c_uint, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvshl(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvlshr(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvashr(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_rotate_left(c: ?*Z3_context, i: c_uint, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_rotate_right(c: ?*Z3_context, i: c_uint, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_ext_rotate_left(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_ext_rotate_right(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_int2bv(c: ?*Z3_context, n: c_uint, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bv2int(c: ?*Z3_context, t1: ?*Z3_ast, is_signed: bool) ?*Z3_ast;
    pub extern fn Z3_mk_bvadd_no_overflow(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast, is_signed: bool) ?*Z3_ast;
    pub extern fn Z3_mk_bvadd_no_underflow(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvsub_no_overflow(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvsub_no_underflow(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast, is_signed: bool) ?*Z3_ast;
    pub extern fn Z3_mk_bvsdiv_no_overflow(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvneg_no_overflow(c: ?*Z3_context, t1: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_bvmul_no_overflow(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast, is_signed: bool) ?*Z3_ast;
    pub extern fn Z3_mk_bvmul_no_underflow(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) ?*Z3_ast;

    // =========================================================
    // Arrays
    // =========================================================
    pub extern fn Z3_mk_select(c: ?*Z3_context, a: ?*Z3_ast, i: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_select_n(c: ?*Z3_context, a: ?*Z3_ast, n: c_uint, idxs: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_store(c: ?*Z3_context, a: ?*Z3_ast, i: ?*Z3_ast, v: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_store_n(c: ?*Z3_context, a: ?*Z3_ast, n: c_uint, idxs: [*]const ?*Z3_ast, v: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_const_array(c: ?*Z3_context, domain: ?*Z3_sort, v: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_map(c: ?*Z3_context, f: ?*Z3_func_decl, n: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_array_default(c: ?*Z3_context, array: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_as_array(c: ?*Z3_context, f: ?*Z3_func_decl) ?*Z3_ast;
    pub extern fn Z3_mk_set_has_size(c: ?*Z3_context, set: ?*Z3_ast, k: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_empty_set(c: ?*Z3_context, domain: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_mk_full_set(c: ?*Z3_context, domain: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_mk_set_add(c: ?*Z3_context, set: ?*Z3_ast, elem: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_set_del(c: ?*Z3_context, set: ?*Z3_ast, elem: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_set_union(c: ?*Z3_context, num_args: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_set_intersect(c: ?*Z3_context, num_args: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_set_difference(c: ?*Z3_context, arg1: ?*Z3_ast, arg2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_set_complement(c: ?*Z3_context, arg: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_set_member(c: ?*Z3_context, elem: ?*Z3_ast, set: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_set_subset(c: ?*Z3_context, arg1: ?*Z3_ast, arg2: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_array_ext(c: ?*Z3_context, arg1: ?*Z3_ast, arg2: ?*Z3_ast) ?*Z3_ast;

    // =========================================================
    // Numerals
    // =========================================================
    pub extern fn Z3_mk_numeral(c: ?*Z3_context, numeral: [*:0]const u8, ty: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_mk_real(c: ?*Z3_context, num: c_int, den: c_int) ?*Z3_ast;
    pub extern fn Z3_mk_int(c: ?*Z3_context, v: c_int, ty: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_mk_unsigned_int(c: ?*Z3_context, v: c_uint, ty: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_mk_int64(c: ?*Z3_context, v: i64, ty: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_mk_unsigned_int64(c: ?*Z3_context, v: u64, ty: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_mk_bv_numeral(c: ?*Z3_context, sz: c_uint, bits: [*]const bool) ?*Z3_ast;

    // =========================================================
    // Quantifiers
    // =========================================================
    pub extern fn Z3_mk_pattern(c: ?*Z3_context, num_patterns: c_uint, terms: [*]const ?*Z3_ast) ?*Z3_pattern;
    pub extern fn Z3_mk_bound(c: ?*Z3_context, index: c_uint, ty: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_mk_forall(c: ?*Z3_context, weight: c_uint, num_patterns: c_uint, patterns: [*]const ?*Z3_pattern, num_decls: c_uint, sorts: [*]const ?*Z3_sort, decl_names: [*]const ?*Z3_symbol, body: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_exists(c: ?*Z3_context, weight: c_uint, num_patterns: c_uint, patterns: [*]const ?*Z3_pattern, num_decls: c_uint, sorts: [*]const ?*Z3_sort, decl_names: [*]const ?*Z3_symbol, body: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_quantifier(c: ?*Z3_context, is_forall: bool, weight: c_uint, num_patterns: c_uint, patterns: [*]const ?*Z3_pattern, num_decls: c_uint, sorts: [*]const ?*Z3_sort, decl_names: [*]const ?*Z3_symbol, body: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_quantifier_ex(c: ?*Z3_context, is_forall: bool, weight: c_uint, quantifier_id: ?*Z3_symbol, skolem_id: ?*Z3_symbol, num_patterns: c_uint, patterns: [*]const ?*Z3_pattern, num_no_patterns: c_uint, no_patterns: [*]const ?*Z3_ast, num_decls: c_uint, sorts: [*]const ?*Z3_sort, decl_names: [*]const ?*Z3_symbol, body: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_forall_const(c: ?*Z3_context, weight: c_uint, num_bound: c_uint, bound: [*]const ?*Z3_app, num_patterns: c_uint, patterns: [*]const ?*Z3_pattern, body: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_exists_const(c: ?*Z3_context, weight: c_uint, num_bound: c_uint, bound: [*]const ?*Z3_app, num_patterns: c_uint, patterns: [*]const ?*Z3_pattern, body: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_lambda(c: ?*Z3_context, num_decls: c_uint, sorts: [*]const ?*Z3_sort, decl_names: [*]const ?*Z3_symbol, body: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_mk_lambda_const(c: ?*Z3_context, num_bound: c_uint, bound: [*]const ?*Z3_app, body: ?*Z3_ast) ?*Z3_ast;

    // =========================================================
    // AST accessors
    // =========================================================
    pub extern fn Z3_get_ast_id(c: ?*Z3_context, t: ?*Z3_ast) c_uint;
    pub extern fn Z3_get_ast_hash(c: ?*Z3_context, a: ?*Z3_ast) c_uint;
    pub extern fn Z3_get_sort(c: ?*Z3_context, a: ?*Z3_ast) ?*Z3_sort;
    pub extern fn Z3_is_well_sorted(c: ?*Z3_context, t: ?*Z3_ast) bool;
    pub extern fn Z3_get_bool_value(c: ?*Z3_context, a: ?*Z3_ast) Z3_lbool;
    pub extern fn Z3_get_ast_kind(c: ?*Z3_context, a: ?*Z3_ast) Z3_ast_kind;
    pub extern fn Z3_is_app(c: ?*Z3_context, a: ?*Z3_ast) bool;
    pub extern fn Z3_is_numeral_ast(c: ?*Z3_context, a: ?*Z3_ast) bool;
    pub extern fn Z3_is_algebraic_number(c: ?*Z3_context, a: ?*Z3_ast) bool;
    pub extern fn Z3_to_app(c: ?*Z3_context, a: ?*Z3_ast) ?*Z3_app;
    pub extern fn Z3_to_func_decl(c: ?*Z3_context, a: ?*Z3_ast) ?*Z3_func_decl;
    pub extern fn Z3_get_numeral_string(c: ?*Z3_context, a: ?*Z3_ast) ?[*:0]const u8;
    pub extern fn Z3_get_numeral_binary_string(c: ?*Z3_context, a: ?*Z3_ast) ?[*:0]const u8;
    pub extern fn Z3_get_numeral_decimal_string(c: ?*Z3_context, a: ?*Z3_ast, precision: c_uint) ?[*:0]const u8;
    pub extern fn Z3_get_numeral_double(c: ?*Z3_context, a: ?*Z3_ast) f64;
    pub extern fn Z3_get_numerator(c: ?*Z3_context, a: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_get_denominator(c: ?*Z3_context, a: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_get_numeral_small(c: ?*Z3_context, a: ?*Z3_ast, num: *i64, den: *i64) bool;
    pub extern fn Z3_get_numeral_int(c: ?*Z3_context, v: ?*Z3_ast, i: *c_int) bool;
    pub extern fn Z3_get_numeral_uint(c: ?*Z3_context, v: ?*Z3_ast, u: *c_uint) bool;
    pub extern fn Z3_get_numeral_uint64(c: ?*Z3_context, v: ?*Z3_ast, u: *u64) bool;
    pub extern fn Z3_get_numeral_int64(c: ?*Z3_context, v: ?*Z3_ast, i: *i64) bool;
    pub extern fn Z3_get_algebraic_number_lower(c: ?*Z3_context, a: ?*Z3_ast, precision: c_uint) ?*Z3_ast;
    pub extern fn Z3_get_algebraic_number_upper(c: ?*Z3_context, a: ?*Z3_ast, precision: c_uint) ?*Z3_ast;
    pub extern fn Z3_pattern_to_ast(c: ?*Z3_context, p: ?*Z3_pattern) ?*Z3_ast;
    pub extern fn Z3_get_pattern_num_terms(c: ?*Z3_context, p: ?*Z3_pattern) c_uint;
    pub extern fn Z3_get_pattern(c: ?*Z3_context, p: ?*Z3_pattern, idx: c_uint) ?*Z3_ast;
    pub extern fn Z3_get_index_value(c: ?*Z3_context, a: ?*Z3_ast) c_uint;
    pub extern fn Z3_is_quantifier_forall(c: ?*Z3_context, a: ?*Z3_ast) bool;
    pub extern fn Z3_is_lambda(c: ?*Z3_context, a: ?*Z3_ast) bool;
    pub extern fn Z3_get_quantifier_weight(c: ?*Z3_context, a: ?*Z3_ast) c_uint;
    pub extern fn Z3_get_quantifier_num_patterns(c: ?*Z3_context, a: ?*Z3_ast) c_uint;
    pub extern fn Z3_get_quantifier_pattern_ast(c: ?*Z3_context, a: ?*Z3_ast, i: c_uint) ?*Z3_pattern;
    pub extern fn Z3_get_quantifier_num_no_patterns(c: ?*Z3_context, a: ?*Z3_ast) c_uint;
    pub extern fn Z3_get_quantifier_no_pattern_ast(c: ?*Z3_context, a: ?*Z3_ast, i: c_uint) ?*Z3_ast;
    pub extern fn Z3_get_quantifier_num_bound(c: ?*Z3_context, a: ?*Z3_ast) c_uint;
    pub extern fn Z3_get_quantifier_bound_name(c: ?*Z3_context, a: ?*Z3_ast, i: c_uint) ?*Z3_symbol;
    pub extern fn Z3_get_quantifier_bound_sort(c: ?*Z3_context, a: ?*Z3_ast, i: c_uint) ?*Z3_sort;
    pub extern fn Z3_get_quantifier_body(c: ?*Z3_context, a: ?*Z3_ast) ?*Z3_ast;

    // App accessors
    pub extern fn Z3_get_app_decl(c: ?*Z3_context, a: ?*Z3_app) ?*Z3_func_decl;
    pub extern fn Z3_get_app_num_args(c: ?*Z3_context, a: ?*Z3_app) c_uint;
    pub extern fn Z3_get_app_arg(c: ?*Z3_context, a: ?*Z3_app, i: c_uint) ?*Z3_ast;

    // Func decl accessors
    pub extern fn Z3_get_decl_name(c: ?*Z3_context, d: ?*Z3_func_decl) ?*Z3_symbol;
    pub extern fn Z3_get_decl_kind(c: ?*Z3_context, d: ?*Z3_func_decl) Z3_decl_kind;
    pub extern fn Z3_get_domain_size(c: ?*Z3_context, d: ?*Z3_func_decl) c_uint;
    pub extern fn Z3_get_arity(c: ?*Z3_context, d: ?*Z3_func_decl) c_uint;
    pub extern fn Z3_get_domain(c: ?*Z3_context, d: ?*Z3_func_decl, i: c_uint) ?*Z3_sort;
    pub extern fn Z3_get_range(c: ?*Z3_context, d: ?*Z3_func_decl) ?*Z3_sort;
    pub extern fn Z3_get_decl_num_parameters(c: ?*Z3_context, d: ?*Z3_func_decl) c_uint;
    pub extern fn Z3_get_decl_parameter_kind(c: ?*Z3_context, d: ?*Z3_func_decl, idx: c_uint) Z3_parameter_kind;
    pub extern fn Z3_get_decl_int_parameter(c: ?*Z3_context, d: ?*Z3_func_decl, idx: c_uint) c_int;
    pub extern fn Z3_get_decl_double_parameter(c: ?*Z3_context, d: ?*Z3_func_decl, idx: c_uint) f64;
    pub extern fn Z3_get_decl_symbol_parameter(c: ?*Z3_context, d: ?*Z3_func_decl, idx: c_uint) ?*Z3_symbol;
    pub extern fn Z3_get_decl_sort_parameter(c: ?*Z3_context, d: ?*Z3_func_decl, idx: c_uint) ?*Z3_sort;
    pub extern fn Z3_get_decl_ast_parameter(c: ?*Z3_context, d: ?*Z3_func_decl, idx: c_uint) ?*Z3_ast;
    pub extern fn Z3_get_decl_func_decl_parameter(c: ?*Z3_context, d: ?*Z3_func_decl, idx: c_uint) ?*Z3_func_decl;
    pub extern fn Z3_get_decl_rational_parameter(c: ?*Z3_context, d: ?*Z3_func_decl, idx: c_uint) ?[*:0]const u8;

    // Sort accessors
    pub extern fn Z3_sort_to_ast(c: ?*Z3_context, s: ?*Z3_sort) ?*Z3_ast;
    pub extern fn Z3_is_eq_sort(c: ?*Z3_context, s1: ?*Z3_sort, s2: ?*Z3_sort) bool;
    pub extern fn Z3_get_sort_name(c: ?*Z3_context, d: ?*Z3_sort) ?*Z3_symbol;
    pub extern fn Z3_get_sort_id(c: ?*Z3_context, s: ?*Z3_sort) c_uint;
    pub extern fn Z3_func_decl_to_ast(c: ?*Z3_context, f: ?*Z3_func_decl) ?*Z3_ast;
    pub extern fn Z3_is_eq_func_decl(c: ?*Z3_context, f1: ?*Z3_func_decl, f2: ?*Z3_func_decl) bool;
    pub extern fn Z3_get_func_decl_id(c: ?*Z3_context, f: ?*Z3_func_decl) c_uint;
    pub extern fn Z3_is_eq_ast(c: ?*Z3_context, t1: ?*Z3_ast, t2: ?*Z3_ast) bool;

    // =========================================================
    // Substitution / simplification
    // =========================================================
    pub extern fn Z3_substitute(c: ?*Z3_context, a: ?*Z3_ast, num_exprs: c_uint, from: [*]const ?*Z3_ast, to: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_substitute_vars(c: ?*Z3_context, a: ?*Z3_ast, num_exprs: c_uint, to: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_substitute_funs(c: ?*Z3_context, a: ?*Z3_ast, num_funs: c_uint, from: [*]const ?*Z3_func_decl, to: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_simplify(c: ?*Z3_context, a: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_simplify_ex(c: ?*Z3_context, a: ?*Z3_ast, p: ?*Z3_params) ?*Z3_ast;
    pub extern fn Z3_simplify_get_help(c: ?*Z3_context) ?[*:0]const u8;
    pub extern fn Z3_simplify_get_param_descrs(c: ?*Z3_context) ?*Z3_param_descrs;

    // =========================================================
    // Modifiers
    // =========================================================
    pub extern fn Z3_update_term(c: ?*Z3_context, a: ?*Z3_ast, num_args: c_uint, args: [*]const ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_translate(source: ?*Z3_context, a: ?*Z3_ast, target: ?*Z3_context) ?*Z3_ast;

    // =========================================================
    // AST vectors
    // =========================================================
    pub extern fn Z3_mk_ast_vector(c: ?*Z3_context) ?*Z3_ast_vector;
    pub extern fn Z3_ast_vector_inc_ref(c: ?*Z3_context, v: ?*Z3_ast_vector) void;
    pub extern fn Z3_ast_vector_dec_ref(c: ?*Z3_context, v: ?*Z3_ast_vector) void;
    pub extern fn Z3_ast_vector_size(c: ?*Z3_context, v: ?*Z3_ast_vector) c_uint;
    pub extern fn Z3_ast_vector_get(c: ?*Z3_context, v: ?*Z3_ast_vector, i: c_uint) ?*Z3_ast;
    pub extern fn Z3_ast_vector_set(c: ?*Z3_context, v: ?*Z3_ast_vector, i: c_uint, a: ?*Z3_ast) void;
    pub extern fn Z3_ast_vector_resize(c: ?*Z3_context, v: ?*Z3_ast_vector, n: c_uint) void;
    pub extern fn Z3_ast_vector_push(c: ?*Z3_context, v: ?*Z3_ast_vector, a: ?*Z3_ast) void;
    pub extern fn Z3_ast_vector_translate(s: ?*Z3_context, v: ?*Z3_ast_vector, t: ?*Z3_context) ?*Z3_ast_vector;
    pub extern fn Z3_ast_vector_to_string(c: ?*Z3_context, v: ?*Z3_ast_vector) ?[*:0]const u8;

    // =========================================================
    // AST maps
    // =========================================================
    pub extern fn Z3_mk_ast_map(c: ?*Z3_context) ?*Z3_ast_map;
    pub extern fn Z3_ast_map_inc_ref(c: ?*Z3_context, m: ?*Z3_ast_map) void;
    pub extern fn Z3_ast_map_dec_ref(c: ?*Z3_context, m: ?*Z3_ast_map) void;
    pub extern fn Z3_ast_map_contains(c: ?*Z3_context, m: ?*Z3_ast_map, k: ?*Z3_ast) bool;
    pub extern fn Z3_ast_map_find(c: ?*Z3_context, m: ?*Z3_ast_map, k: ?*Z3_ast) ?*Z3_ast;
    pub extern fn Z3_ast_map_insert(c: ?*Z3_context, m: ?*Z3_ast_map, k: ?*Z3_ast, v: ?*Z3_ast) void;
    pub extern fn Z3_ast_map_erase(c: ?*Z3_context, m: ?*Z3_ast_map, k: ?*Z3_ast) void;
    pub extern fn Z3_ast_map_reset(c: ?*Z3_context, m: ?*Z3_ast_map) void;
    pub extern fn Z3_ast_map_size(c: ?*Z3_context, m: ?*Z3_ast_map) c_uint;
    pub extern fn Z3_ast_map_keys(c: ?*Z3_context, m: ?*Z3_ast_map) ?*Z3_ast_vector;
    pub extern fn Z3_ast_map_to_string(c: ?*Z3_context, m: ?*Z3_ast_map) ?[*:0]const u8;

    // =========================================================
    // Model
    // =========================================================
    pub extern fn Z3_model_inc_ref(c: ?*Z3_context, m: ?*Z3_model) void;
    pub extern fn Z3_model_dec_ref(c: ?*Z3_context, m: ?*Z3_model) void;
    pub extern fn Z3_model_eval(c: ?*Z3_context, m: ?*Z3_model, t: ?*Z3_ast, model_completion: bool, v: *?*Z3_ast) bool;
    pub extern fn Z3_model_get_const_interp(c: ?*Z3_context, m: ?*Z3_model, a: ?*Z3_func_decl) ?*Z3_ast;
    pub extern fn Z3_model_has_interp(c: ?*Z3_context, m: ?*Z3_model, a: ?*Z3_func_decl) bool;
    pub extern fn Z3_model_get_func_interp(c: ?*Z3_context, m: ?*Z3_model, f: ?*Z3_func_decl) ?*Z3_func_interp;
    pub extern fn Z3_model_get_num_consts(c: ?*Z3_context, m: ?*Z3_model) c_uint;
    pub extern fn Z3_model_get_const_decl(c: ?*Z3_context, m: ?*Z3_model, i: c_uint) ?*Z3_func_decl;
    pub extern fn Z3_model_get_num_funcs(c: ?*Z3_context, m: ?*Z3_model) c_uint;
    pub extern fn Z3_model_get_func_decl(c: ?*Z3_context, m: ?*Z3_model, i: c_uint) ?*Z3_func_decl;
    pub extern fn Z3_model_get_num_sorts(c: ?*Z3_context, m: ?*Z3_model) c_uint;
    pub extern fn Z3_model_get_sort(c: ?*Z3_context, m: ?*Z3_model, i: c_uint) ?*Z3_sort;
    pub extern fn Z3_model_get_sort_universe(c: ?*Z3_context, m: ?*Z3_model, s: ?*Z3_sort) ?*Z3_ast_vector;
    pub extern fn Z3_model_translate(c: ?*Z3_context, m: ?*Z3_model, dst: ?*Z3_context) ?*Z3_model;
    pub extern fn Z3_is_as_array(c: ?*Z3_context, n: ?*Z3_ast) bool;
    pub extern fn Z3_get_as_array_func_decl(c: ?*Z3_context, n: ?*Z3_ast) ?*Z3_func_decl;
    pub extern fn Z3_func_interp_inc_ref(c: ?*Z3_context, f: ?*Z3_func_interp) void;
    pub extern fn Z3_func_interp_dec_ref(c: ?*Z3_context, f: ?*Z3_func_interp) void;
    pub extern fn Z3_func_interp_get_num_entries(c: ?*Z3_context, f: ?*Z3_func_interp) c_uint;
    pub extern fn Z3_func_interp_get_entry(c: ?*Z3_context, f: ?*Z3_func_interp, i: c_uint) ?*Z3_func_entry;
    pub extern fn Z3_func_interp_get_else(c: ?*Z3_context, f: ?*Z3_func_interp) ?*Z3_ast;
    pub extern fn Z3_func_interp_get_arity(c: ?*Z3_context, f: ?*Z3_func_interp) c_uint;
    pub extern fn Z3_func_interp_add_entry(c: ?*Z3_context, fi: ?*Z3_func_interp, args: ?*Z3_ast_vector, value: ?*Z3_ast) void;
    pub extern fn Z3_func_interp_set_else(c: ?*Z3_context, fi: ?*Z3_func_interp, else_value: ?*Z3_ast) void;
    pub extern fn Z3_func_entry_inc_ref(c: ?*Z3_context, e: ?*Z3_func_entry) void;
    pub extern fn Z3_func_entry_dec_ref(c: ?*Z3_context, e: ?*Z3_func_entry) void;
    pub extern fn Z3_func_entry_get_value(c: ?*Z3_context, e: ?*Z3_func_entry) ?*Z3_ast;
    pub extern fn Z3_func_entry_get_num_args(c: ?*Z3_context, e: ?*Z3_func_entry) c_uint;
    pub extern fn Z3_func_entry_get_arg(c: ?*Z3_context, e: ?*Z3_func_entry, i: c_uint) ?*Z3_ast;

    // =========================================================
    // Interaction logs / strings
    // =========================================================
    pub extern fn Z3_open_log(filename: [*:0]const u8) bool;
    pub extern fn Z3_append_log(string: [*:0]const u8) void;
    pub extern fn Z3_close_log() void;
    pub extern fn Z3_toggle_warning_messages(enabled: bool) void;
    pub extern fn Z3_ast_to_string(c: ?*Z3_context, a: ?*Z3_ast) ?[*:0]const u8;
    pub extern fn Z3_pattern_to_string(c: ?*Z3_context, p: ?*Z3_pattern) ?[*:0]const u8;
    pub extern fn Z3_sort_to_string(c: ?*Z3_context, s: ?*Z3_sort) ?[*:0]const u8;
    pub extern fn Z3_func_decl_to_string(c: ?*Z3_context, d: ?*Z3_func_decl) ?[*:0]const u8;
    pub extern fn Z3_model_to_string(c: ?*Z3_context, m: ?*Z3_model) ?[*:0]const u8;
    pub extern fn Z3_benchmark_to_smtlib_string(c: ?*Z3_context, name: ?[*:0]const u8, logic: ?[*:0]const u8, status: ?[*:0]const u8, attributes: ?[*:0]const u8, num_assumptions: c_uint, assumptions: [*]const ?*Z3_ast, formula: ?*Z3_ast) ?[*:0]const u8;

    // =========================================================
    // Parser interface
    // =========================================================
    pub extern fn Z3_mk_parser_context(c: ?*Z3_context) ?*Z3_parser_context;
    pub extern fn Z3_parser_context_inc_ref(c: ?*Z3_context, pc: ?*Z3_parser_context) void;
    pub extern fn Z3_parser_context_dec_ref(c: ?*Z3_context, pc: ?*Z3_parser_context) void;
    pub extern fn Z3_parser_context_add_sort(c: ?*Z3_context, pc: ?*Z3_parser_context, s: ?*Z3_sort) void;
    pub extern fn Z3_parser_context_add_decl(c: ?*Z3_context, pc: ?*Z3_parser_context, f: ?*Z3_func_decl) void;
    pub extern fn Z3_parser_context_from_string(c: ?*Z3_context, pc: ?*Z3_parser_context, s: [*:0]const u8) ?*Z3_ast_vector;
    pub extern fn Z3_parse_smtlib2_string(c: ?*Z3_context, str: [*:0]const u8, num_sorts: c_uint, sort_names: [*]const ?*Z3_symbol, sorts: [*]const ?*Z3_sort, num_decls: c_uint, decl_names: [*]const ?*Z3_symbol, decls: [*]const ?*Z3_func_decl) ?*Z3_ast_vector;
    pub extern fn Z3_parse_smtlib2_file(c: ?*Z3_context, file_name: [*:0]const u8, num_sorts: c_uint, sort_names: [*]const ?*Z3_symbol, sorts: [*]const ?*Z3_sort, num_decls: c_uint, decl_names: [*]const ?*Z3_symbol, decls: [*]const ?*Z3_func_decl) ?*Z3_ast_vector;
    pub extern fn Z3_eval_smtlib2_string(c: ?*Z3_context, s: [*:0]const u8) ?[*:0]const u8;

    // =========================================================
    // Error handling
    // =========================================================
    pub extern fn Z3_get_error_code(c: ?*Z3_context) Z3_error_code;
    pub extern fn Z3_set_error_handler(c: ?*Z3_context, h: Z3_error_handler) void;
    pub extern fn Z3_set_error(c: ?*Z3_context, e: Z3_error_code) void;
    pub extern fn Z3_get_error_msg(c: ?*Z3_context, err: Z3_error_code) ?[*:0]const u8;

    // =========================================================
    // Version
    // =========================================================
    pub extern fn Z3_get_version(major: *c_uint, minor: *c_uint, build_number: *c_uint, revision_number: *c_uint) void;
    pub extern fn Z3_get_full_version() ?[*:0]const u8;
    pub extern fn Z3_enable_trace(tag: [*:0]const u8) void;
    pub extern fn Z3_disable_trace(tag: [*:0]const u8) void;
    pub extern fn Z3_reset_memory() void;
    pub extern fn Z3_finalize_memory() void;

    // =========================================================
    // Goals
    // =========================================================
    pub extern fn Z3_mk_goal(c: ?*Z3_context, models: bool, unsat_cores: bool, proofs: bool) ?*Z3_goal;
    pub extern fn Z3_goal_inc_ref(c: ?*Z3_context, g: ?*Z3_goal) void;
    pub extern fn Z3_goal_dec_ref(c: ?*Z3_context, g: ?*Z3_goal) void;
    pub extern fn Z3_goal_precision(c: ?*Z3_context, g: ?*Z3_goal) Z3_goal_prec;
    pub extern fn Z3_goal_assert(c: ?*Z3_context, g: ?*Z3_goal, a: ?*Z3_ast) void;
    pub extern fn Z3_goal_inconsistent(c: ?*Z3_context, g: ?*Z3_goal) bool;
    pub extern fn Z3_goal_depth(c: ?*Z3_context, g: ?*Z3_goal) c_uint;
    pub extern fn Z3_goal_reset(c: ?*Z3_context, g: ?*Z3_goal) void;
    pub extern fn Z3_goal_size(c: ?*Z3_context, g: ?*Z3_goal) c_uint;
    pub extern fn Z3_goal_formula(c: ?*Z3_context, g: ?*Z3_goal, idx: c_uint) ?*Z3_ast;
    pub extern fn Z3_goal_num_exprs(c: ?*Z3_context, g: ?*Z3_goal) c_uint;
    pub extern fn Z3_goal_is_decided_sat(c: ?*Z3_context, g: ?*Z3_goal) bool;
    pub extern fn Z3_goal_is_decided_unsat(c: ?*Z3_context, g: ?*Z3_goal) bool;
    pub extern fn Z3_goal_translate(source: ?*Z3_context, g: ?*Z3_goal, target: ?*Z3_context) ?*Z3_goal;
    pub extern fn Z3_goal_convert_model(c: ?*Z3_context, g: ?*Z3_goal, m: ?*Z3_model) ?*Z3_model;
    pub extern fn Z3_goal_to_string(c: ?*Z3_context, g: ?*Z3_goal) ?[*:0]const u8;
    pub extern fn Z3_goal_to_dimacs_string(c: ?*Z3_context, g: ?*Z3_goal, include_names: bool) ?[*:0]const u8;

    // =========================================================
    // Tactics
    // =========================================================
    pub extern fn Z3_mk_tactic(c: ?*Z3_context, name: [*:0]const u8) ?*Z3_tactic;
    pub extern fn Z3_tactic_inc_ref(c: ?*Z3_context, t: ?*Z3_tactic) void;
    pub extern fn Z3_tactic_dec_ref(c: ?*Z3_context, t: ?*Z3_tactic) void;
    pub extern fn Z3_mk_probe(c: ?*Z3_context, name: [*:0]const u8) ?*Z3_probe;
    pub extern fn Z3_probe_inc_ref(c: ?*Z3_context, p: ?*Z3_probe) void;
    pub extern fn Z3_probe_dec_ref(c: ?*Z3_context, p: ?*Z3_probe) void;
    pub extern fn Z3_tactic_and_then(c: ?*Z3_context, t1: ?*Z3_tactic, t2: ?*Z3_tactic) ?*Z3_tactic;
    pub extern fn Z3_tactic_or_else(c: ?*Z3_context, t1: ?*Z3_tactic, t2: ?*Z3_tactic) ?*Z3_tactic;
    pub extern fn Z3_tactic_par_or(c: ?*Z3_context, num: c_uint, ts: [*]const ?*Z3_tactic) ?*Z3_tactic;
    pub extern fn Z3_tactic_par_and_then(c: ?*Z3_context, t1: ?*Z3_tactic, t2: ?*Z3_tactic) ?*Z3_tactic;
    pub extern fn Z3_tactic_try_for(c: ?*Z3_context, t: ?*Z3_tactic, ms: c_uint) ?*Z3_tactic;
    pub extern fn Z3_tactic_when(c: ?*Z3_context, p: ?*Z3_probe, t: ?*Z3_tactic) ?*Z3_tactic;
    pub extern fn Z3_tactic_cond(c: ?*Z3_context, p: ?*Z3_probe, t1: ?*Z3_tactic, t2: ?*Z3_tactic) ?*Z3_tactic;
    pub extern fn Z3_tactic_repeat(c: ?*Z3_context, t: ?*Z3_tactic, max: c_uint) ?*Z3_tactic;
    pub extern fn Z3_tactic_skip(c: ?*Z3_context) ?*Z3_tactic;
    pub extern fn Z3_tactic_fail(c: ?*Z3_context) ?*Z3_tactic;
    pub extern fn Z3_tactic_fail_if(c: ?*Z3_context, p: ?*Z3_probe) ?*Z3_tactic;
    pub extern fn Z3_tactic_fail_if_not_decided(c: ?*Z3_context) ?*Z3_tactic;
    pub extern fn Z3_tactic_using_params(c: ?*Z3_context, t: ?*Z3_tactic, p: ?*Z3_params) ?*Z3_tactic;
    pub extern fn Z3_probe_const(x: ?*Z3_context, val: f64) ?*Z3_probe;
    pub extern fn Z3_probe_lt(c: ?*Z3_context, p1: ?*Z3_probe, p2: ?*Z3_probe) ?*Z3_probe;
    pub extern fn Z3_probe_gt(c: ?*Z3_context, p1: ?*Z3_probe, p2: ?*Z3_probe) ?*Z3_probe;
    pub extern fn Z3_probe_le(c: ?*Z3_context, p1: ?*Z3_probe, p2: ?*Z3_probe) ?*Z3_probe;
    pub extern fn Z3_probe_ge(c: ?*Z3_context, p1: ?*Z3_probe, p2: ?*Z3_probe) ?*Z3_probe;
    pub extern fn Z3_probe_eq(c: ?*Z3_context, p1: ?*Z3_probe, p2: ?*Z3_probe) ?*Z3_probe;
    pub extern fn Z3_probe_and(c: ?*Z3_context, p1: ?*Z3_probe, p2: ?*Z3_probe) ?*Z3_probe;
    pub extern fn Z3_probe_or(c: ?*Z3_context, p1: ?*Z3_probe, p2: ?*Z3_probe) ?*Z3_probe;
    pub extern fn Z3_probe_not(c: ?*Z3_context, p: ?*Z3_probe) ?*Z3_probe;
    pub extern fn Z3_get_num_tactics(c: ?*Z3_context) c_uint;
    pub extern fn Z3_get_tactic_name(c: ?*Z3_context, i: c_uint) ?[*:0]const u8;
    pub extern fn Z3_get_num_probes(c: ?*Z3_context) c_uint;
    pub extern fn Z3_get_probe_name(c: ?*Z3_context, i: c_uint) ?[*:0]const u8;
    pub extern fn Z3_tactic_get_help(c: ?*Z3_context, t: ?*Z3_tactic) ?[*:0]const u8;
    pub extern fn Z3_tactic_get_param_descrs(c: ?*Z3_context, t: ?*Z3_tactic) ?*Z3_param_descrs;
    pub extern fn Z3_tactic_get_descr(c: ?*Z3_context, name: [*:0]const u8) ?[*:0]const u8;
    pub extern fn Z3_probe_get_descr(c: ?*Z3_context, name: [*:0]const u8) ?[*:0]const u8;
    pub extern fn Z3_probe_apply(c: ?*Z3_context, p: ?*Z3_probe, g: ?*Z3_goal) f64;
    pub extern fn Z3_tactic_apply(c: ?*Z3_context, t: ?*Z3_tactic, g: ?*Z3_goal) ?*Z3_apply_result;
    pub extern fn Z3_tactic_apply_ex(c: ?*Z3_context, t: ?*Z3_tactic, g: ?*Z3_goal, p: ?*Z3_params) ?*Z3_apply_result;
    pub extern fn Z3_apply_result_inc_ref(c: ?*Z3_context, r: ?*Z3_apply_result) void;
    pub extern fn Z3_apply_result_dec_ref(c: ?*Z3_context, r: ?*Z3_apply_result) void;
    pub extern fn Z3_apply_result_to_string(c: ?*Z3_context, r: ?*Z3_apply_result) ?[*:0]const u8;
    pub extern fn Z3_apply_result_get_num_subgoals(c: ?*Z3_context, r: ?*Z3_apply_result) c_uint;
    pub extern fn Z3_apply_result_get_subgoal(c: ?*Z3_context, r: ?*Z3_apply_result, i: c_uint) ?*Z3_goal;

    // =========================================================
    // Solver
    // =========================================================
    pub extern fn Z3_mk_solver(c: ?*Z3_context) ?*Z3_solver;
    pub extern fn Z3_mk_solver_for_logic(c: ?*Z3_context, logic: ?*Z3_symbol) ?*Z3_solver;
    pub extern fn Z3_mk_solver_from_tactic(c: ?*Z3_context, t: ?*Z3_tactic) ?*Z3_solver;
    pub extern fn Z3_mk_simple_solver(c: ?*Z3_context) ?*Z3_solver;
    pub extern fn Z3_solver_get_help(c: ?*Z3_context, s: ?*Z3_solver) ?[*:0]const u8;
    pub extern fn Z3_solver_get_param_descrs(c: ?*Z3_context, s: ?*Z3_solver) ?*Z3_param_descrs;
    pub extern fn Z3_solver_set_params(c: ?*Z3_context, s: ?*Z3_solver, p: ?*Z3_params) void;
    pub extern fn Z3_solver_inc_ref(c: ?*Z3_context, s: ?*Z3_solver) void;
    pub extern fn Z3_solver_dec_ref(c: ?*Z3_context, s: ?*Z3_solver) void;
    pub extern fn Z3_solver_interrupt(c: ?*Z3_context, s: ?*Z3_solver) void;
    pub extern fn Z3_solver_push(c: ?*Z3_context, s: ?*Z3_solver) void;
    pub extern fn Z3_solver_pop(c: ?*Z3_context, s: ?*Z3_solver, n: c_uint) void;
    pub extern fn Z3_solver_reset(c: ?*Z3_context, s: ?*Z3_solver) void;
    pub extern fn Z3_solver_get_num_scopes(c: ?*Z3_context, s: ?*Z3_solver) c_uint;
    pub extern fn Z3_solver_assert(c: ?*Z3_context, s: ?*Z3_solver, a: ?*Z3_ast) void;
    pub extern fn Z3_solver_assert_and_track(c: ?*Z3_context, s: ?*Z3_solver, a: ?*Z3_ast, p: ?*Z3_ast) void;
    pub extern fn Z3_solver_from_file(c: ?*Z3_context, s: ?*Z3_solver, file_name: [*:0]const u8) void;
    pub extern fn Z3_solver_from_string(c: ?*Z3_context, s: ?*Z3_solver, file_name: [*:0]const u8) void;
    pub extern fn Z3_solver_get_assertions(c: ?*Z3_context, s: ?*Z3_solver) ?*Z3_ast_vector;
    pub extern fn Z3_solver_get_units(c: ?*Z3_context, s: ?*Z3_solver) ?*Z3_ast_vector;
    pub extern fn Z3_solver_get_trail(c: ?*Z3_context, s: ?*Z3_solver) ?*Z3_ast_vector;
    pub extern fn Z3_solver_get_non_units(c: ?*Z3_context, s: ?*Z3_solver) ?*Z3_ast_vector;
    pub extern fn Z3_solver_get_levels(c: ?*Z3_context, s: ?*Z3_solver, literals: ?*Z3_ast_vector, sz: c_uint, levels: [*]c_uint) void;
    pub extern fn Z3_solver_check(c: ?*Z3_context, s: ?*Z3_solver) Z3_lbool;
    pub extern fn Z3_solver_check_assumptions(c: ?*Z3_context, s: ?*Z3_solver, num_assumptions: c_uint, assumptions: [*]const ?*Z3_ast) Z3_lbool;
    pub extern fn Z3_solver_cube(c: ?*Z3_context, s: ?*Z3_solver, vars: ?*Z3_ast_vector, backtrack_level: c_uint) ?*Z3_ast_vector;
    pub extern fn Z3_solver_get_model(c: ?*Z3_context, s: ?*Z3_solver) ?*Z3_model;
    pub extern fn Z3_solver_get_proof(c: ?*Z3_context, s: ?*Z3_solver) ?*Z3_ast;
    pub extern fn Z3_solver_get_unsat_core(c: ?*Z3_context, s: ?*Z3_solver) ?*Z3_ast_vector;
    pub extern fn Z3_solver_get_reason_unknown(c: ?*Z3_context, s: ?*Z3_solver) ?[*:0]const u8;
    pub extern fn Z3_solver_get_statistics(c: ?*Z3_context, s: ?*Z3_solver) ?*Z3_stats;
    pub extern fn Z3_solver_to_string(c: ?*Z3_context, s: ?*Z3_solver) ?[*:0]const u8;
    pub extern fn Z3_solver_to_dimacs_string(c: ?*Z3_context, s: ?*Z3_solver, include_names: bool) ?[*:0]const u8;

    // =========================================================
    // Statistics
    // =========================================================
    pub extern fn Z3_stats_to_string(c: ?*Z3_context, s: ?*Z3_stats) ?[*:0]const u8;
    pub extern fn Z3_stats_inc_ref(c: ?*Z3_context, s: ?*Z3_stats) void;
    pub extern fn Z3_stats_dec_ref(c: ?*Z3_context, s: ?*Z3_stats) void;
    pub extern fn Z3_stats_size(c: ?*Z3_context, s: ?*Z3_stats) c_uint;
    pub extern fn Z3_stats_get_key(c: ?*Z3_context, s: ?*Z3_stats, idx: c_uint) ?[*:0]const u8;
    pub extern fn Z3_stats_is_uint(c: ?*Z3_context, s: ?*Z3_stats, idx: c_uint) bool;
    pub extern fn Z3_stats_is_double(c: ?*Z3_context, s: ?*Z3_stats, idx: c_uint) bool;
    pub extern fn Z3_stats_get_uint_value(c: ?*Z3_context, s: ?*Z3_stats, idx: c_uint) c_uint;
    pub extern fn Z3_stats_get_double_value(c: ?*Z3_context, s: ?*Z3_stats, idx: c_uint) f64;

    // =========================================================
    // Fixedpoint
    // =========================================================
    pub extern fn Z3_mk_fixedpoint(c: ?*Z3_context) ?*Z3_fixedpoint;
    pub extern fn Z3_fixedpoint_inc_ref(c: ?*Z3_context, d: ?*Z3_fixedpoint) void;
    pub extern fn Z3_fixedpoint_dec_ref(c: ?*Z3_context, d: ?*Z3_fixedpoint) void;
    pub extern fn Z3_fixedpoint_add_rule(c: ?*Z3_context, d: ?*Z3_fixedpoint, rule: ?*Z3_ast, name: ?*Z3_symbol) void;
    pub extern fn Z3_fixedpoint_add_fact(c: ?*Z3_context, d: ?*Z3_fixedpoint, r: ?*Z3_func_decl, num_args: c_uint, args: [*]const c_uint) void;
    pub extern fn Z3_fixedpoint_assert(c: ?*Z3_context, d: ?*Z3_fixedpoint, axiom: ?*Z3_ast) void;
    pub extern fn Z3_fixedpoint_query(c: ?*Z3_context, d: ?*Z3_fixedpoint, query: ?*Z3_ast) Z3_lbool;
    pub extern fn Z3_fixedpoint_query_relations(c: ?*Z3_context, d: ?*Z3_fixedpoint, num_relations: c_uint, relations: [*]const ?*Z3_func_decl) Z3_lbool;
    pub extern fn Z3_fixedpoint_get_answer(c: ?*Z3_context, d: ?*Z3_fixedpoint) ?*Z3_ast;
    pub extern fn Z3_fixedpoint_get_reason_unknown(c: ?*Z3_context, d: ?*Z3_fixedpoint) ?[*:0]const u8;
    pub extern fn Z3_fixedpoint_update_rule(c: ?*Z3_context, d: ?*Z3_fixedpoint, a: ?*Z3_ast, name: ?*Z3_symbol) void;
    pub extern fn Z3_fixedpoint_get_num_levels(c: ?*Z3_context, d: ?*Z3_fixedpoint, pred: ?*Z3_func_decl) c_uint;
    pub extern fn Z3_fixedpoint_get_cover_delta(c: ?*Z3_context, d: ?*Z3_fixedpoint, level: c_int, pred: ?*Z3_func_decl) ?*Z3_ast;
    pub extern fn Z3_fixedpoint_add_cover(c: ?*Z3_context, d: ?*Z3_fixedpoint, level: c_int, pred: ?*Z3_func_decl, property: ?*Z3_ast) void;
    pub extern fn Z3_fixedpoint_get_statistics(c: ?*Z3_context, d: ?*Z3_fixedpoint) ?*Z3_stats;
    pub extern fn Z3_fixedpoint_register_relation(c: ?*Z3_context, d: ?*Z3_fixedpoint, f: ?*Z3_func_decl) void;
    pub extern fn Z3_fixedpoint_set_predicate_representation(c: ?*Z3_context, d: ?*Z3_fixedpoint, f: ?*Z3_func_decl, num_relations: c_uint, relation_kinds: [*]const ?*Z3_symbol) void;
    pub extern fn Z3_fixedpoint_get_rules(c: ?*Z3_context, d: ?*Z3_fixedpoint) ?*Z3_ast_vector;
    pub extern fn Z3_fixedpoint_get_assertions(c: ?*Z3_context, d: ?*Z3_fixedpoint) ?*Z3_ast_vector;
    pub extern fn Z3_fixedpoint_set_params(c: ?*Z3_context, d: ?*Z3_fixedpoint, p: ?*Z3_params) void;
    pub extern fn Z3_fixedpoint_get_help(c: ?*Z3_context, d: ?*Z3_fixedpoint) ?[*:0]const u8;
    pub extern fn Z3_fixedpoint_get_param_descrs(c: ?*Z3_context, d: ?*Z3_fixedpoint) ?*Z3_param_descrs;
    pub extern fn Z3_fixedpoint_to_string(c: ?*Z3_context, d: ?*Z3_fixedpoint, num_queries: c_uint, queries: [*]const ?*Z3_ast) ?[*:0]const u8;
    pub extern fn Z3_fixedpoint_from_string(c: ?*Z3_context, d: ?*Z3_fixedpoint, s: [*:0]const u8) ?*Z3_ast_vector;
    pub extern fn Z3_fixedpoint_from_file(c: ?*Z3_context, d: ?*Z3_fixedpoint, s: [*:0]const u8) ?*Z3_ast_vector;

    // =========================================================
    // Optimize
    // =========================================================
    pub extern fn Z3_mk_optimize(c: ?*Z3_context) ?*Z3_optimize;
    pub extern fn Z3_optimize_inc_ref(c: ?*Z3_context, d: ?*Z3_optimize) void;
    pub extern fn Z3_optimize_dec_ref(c: ?*Z3_context, d: ?*Z3_optimize) void;
    pub extern fn Z3_optimize_assert(c: ?*Z3_context, o: ?*Z3_optimize, a: ?*Z3_ast) void;
    pub extern fn Z3_optimize_assert_soft(c: ?*Z3_context, o: ?*Z3_optimize, a: ?*Z3_ast, weight: [*:0]const u8, id: ?*Z3_symbol) c_uint;
    pub extern fn Z3_optimize_maximize(c: ?*Z3_context, o: ?*Z3_optimize, t: ?*Z3_ast) c_uint;
    pub extern fn Z3_optimize_minimize(c: ?*Z3_context, o: ?*Z3_optimize, t: ?*Z3_ast) c_uint;
    pub extern fn Z3_optimize_push(c: ?*Z3_context, d: ?*Z3_optimize) void;
    pub extern fn Z3_optimize_pop(c: ?*Z3_context, d: ?*Z3_optimize) void;
    pub extern fn Z3_optimize_check(c: ?*Z3_context, o: ?*Z3_optimize, num_assumptions: c_uint, assumptions: [*]const ?*Z3_ast) Z3_lbool;
    pub extern fn Z3_optimize_get_reason_unknown(c: ?*Z3_context, d: ?*Z3_optimize) ?[*:0]const u8;
    pub extern fn Z3_optimize_get_model(c: ?*Z3_context, o: ?*Z3_optimize) ?*Z3_model;
    pub extern fn Z3_optimize_get_unsat_core(c: ?*Z3_context, o: ?*Z3_optimize) ?*Z3_ast_vector;
    pub extern fn Z3_optimize_set_params(c: ?*Z3_context, o: ?*Z3_optimize, p: ?*Z3_params) void;
    pub extern fn Z3_optimize_get_param_descrs(c: ?*Z3_context, o: ?*Z3_optimize) ?*Z3_param_descrs;
    pub extern fn Z3_optimize_get_lower(c: ?*Z3_context, o: ?*Z3_optimize, idx: c_uint) ?*Z3_ast;
    pub extern fn Z3_optimize_get_upper(c: ?*Z3_context, o: ?*Z3_optimize, idx: c_uint) ?*Z3_ast;
    pub extern fn Z3_optimize_get_lower_as_vector(c: ?*Z3_context, o: ?*Z3_optimize, idx: c_uint) ?*Z3_ast_vector;
    pub extern fn Z3_optimize_get_upper_as_vector(c: ?*Z3_context, o: ?*Z3_optimize, idx: c_uint) ?*Z3_ast_vector;
    pub extern fn Z3_optimize_to_string(c: ?*Z3_context, o: ?*Z3_optimize) ?[*:0]const u8;
    pub extern fn Z3_optimize_from_string(c: ?*Z3_context, o: ?*Z3_optimize, s: [*:0]const u8) void;
    pub extern fn Z3_optimize_from_file(c: ?*Z3_context, o: ?*Z3_optimize, s: [*:0]const u8) void;
    pub extern fn Z3_optimize_get_help(c: ?*Z3_context, t: ?*Z3_optimize) ?[*:0]const u8;
    pub extern fn Z3_optimize_get_statistics(c: ?*Z3_context, d: ?*Z3_optimize) ?*Z3_stats;
    pub extern fn Z3_optimize_get_assertions(c: ?*Z3_context, o: ?*Z3_optimize) ?*Z3_ast_vector;
    pub extern fn Z3_optimize_get_objectives(c: ?*Z3_context, o: ?*Z3_optimize) ?*Z3_ast_vector;
};

// ============================================================
// Higher-level idiomatic Zig wrappers
// ============================================================

pub const Error = error{
    Z3SortError,
    Z3IOB,
    Z3InvalidArg,
    Z3ParserError,
    Z3NoParser,
    Z3InvalidPattern,
    Z3MemoutFail,
    Z3FileAccessError,
    Z3InternalFatal,
    Z3InvalidUsage,
    Z3DecRefError,
    Z3Exception,
    Z3NullResult,
};

fn checkError(ctx: *z3.Z3_context) Error!void {
    const code = z3.Z3_get_error_code(ctx);
    return switch (code) {
        .OK => {},
        .SORT_ERROR => Error.Z3SortError,
        .IOB => Error.Z3IOB,
        .INVALID_ARG => Error.Z3InvalidArg,
        .PARSER_ERROR => Error.Z3ParserError,
        .NO_PARSER => Error.Z3NoParser,
        .INVALID_PATTERN => Error.Z3InvalidPattern,
        .MEMOUT_FAIL => Error.Z3MemoutFail,
        .FILE_ACCESS_ERROR => Error.Z3FileAccessError,
        .INTERNAL_FATAL => Error.Z3InternalFatal,
        .INVALID_USAGE => Error.Z3InvalidUsage,
        .DEC_REF_ERROR => Error.Z3DecRefError,
        .EXCEPTION => Error.Z3Exception,
    };
}

// ---- Config ----

pub const Config = struct {
    raw: *z3.Z3_config,

    pub fn init() Config {
        return .{ .raw = z3.Z3_mk_config().? };
    }

    pub fn deinit(self: Config) void {
        z3.Z3_del_config(self.raw);
    }

    pub fn set(self: Config, param: [:0]const u8, value: [:0]const u8) void {
        z3.Z3_set_param_value(self.raw, param, value);
    }
};

// ---- Context ----

pub const Context = struct {
    raw: *z3.Z3_context,

    pub fn init(cfg: Config) Context {
        return .{ .raw = z3.Z3_mk_context(cfg.raw).? };
    }

    /// Create a reference-counted context (use inc_ref/dec_ref on ASTs).
    pub fn initRc(cfg: Config) Context {
        return .{ .raw = z3.Z3_mk_context_rc(cfg.raw).? };
    }

    pub fn deinit(self: Context) void {
        z3.Z3_del_context(self.raw);
    }

    pub fn setErrorHandler(self: Context, handler: z3.Z3_error_handler) void {
        z3.Z3_set_error_handler(self.raw, handler);
    }

    // ---- Sorts ----

    pub fn boolSort(self: Context) Sort {
        return .{ .raw = z3.Z3_mk_bool_sort(self.raw).?, .ctx = self.raw };
    }
    pub fn intSort(self: Context) Sort {
        return .{ .raw = z3.Z3_mk_int_sort(self.raw).?, .ctx = self.raw };
    }
    pub fn realSort(self: Context) Sort {
        return .{ .raw = z3.Z3_mk_real_sort(self.raw).?, .ctx = self.raw };
    }
    pub fn bvSort(self: Context, size: u32) Sort {
        return .{ .raw = z3.Z3_mk_bv_sort(self.raw, @intCast(size)).?, .ctx = self.raw };
    }
    pub fn arraySort(self: Context, domain: Sort, range: Sort) Sort {
        return .{ .raw = z3.Z3_mk_array_sort(self.raw, domain.raw, range.raw).?, .ctx = self.raw };
    }

    // ---- Constants ----
    pub fn boolConst(self: Context, name: [:0]const u8) Ast {
        const sym = z3.Z3_mk_string_symbol(self.raw, name).?;
        const sort = z3.Z3_mk_bool_sort(self.raw).?;
        return .{ .raw = z3.Z3_mk_const(self.raw, sym, sort).?, .ctx = self.raw };
    }
    pub fn intConst(self: Context, name: [:0]const u8) Ast {
        const sym = z3.Z3_mk_string_symbol(self.raw, name).?;
        const sort = z3.Z3_mk_int_sort(self.raw).?;
        return .{ .raw = z3.Z3_mk_const(self.raw, sym, sort).?, .ctx = self.raw };
    }
    pub fn realConst(self: Context, name: [:0]const u8) Ast {
        const sym = z3.Z3_mk_string_symbol(self.raw, name).?;
        const sort = z3.Z3_mk_real_sort(self.raw).?;
        return .{ .raw = z3.Z3_mk_const(self.raw, sym, sort).?, .ctx = self.raw };
    }
    pub fn bvConst(self: Context, name: [:0]const u8, size: u32) Ast {
        const sym = z3.Z3_mk_string_symbol(self.raw, name).?;
        const sort = z3.Z3_mk_bv_sort(self.raw, @intCast(size)).?;
        return .{ .raw = z3.Z3_mk_const(self.raw, sym, sort).?, .ctx = self.raw };
    }

    // ---- Literals ----
    pub fn mkTrue(self: Context) Ast {
        return .{ .raw = z3.Z3_mk_true(self.raw).?, .ctx = self.raw };
    }
    pub fn mkFalse(self: Context) Ast {
        return .{ .raw = z3.Z3_mk_false(self.raw).?, .ctx = self.raw };
    }
    pub fn mkInt(self: Context, v: i64) Ast {
        const sort = z3.Z3_mk_int_sort(self.raw).?;
        return .{ .raw = z3.Z3_mk_int64(self.raw, v, sort).?, .ctx = self.raw };
    }
    pub fn mkUnsignedInt(self: Context, v: u64) Ast {
        const sort = z3.Z3_mk_int_sort(self.raw).?;
        return .{ .raw = z3.Z3_mk_unsigned_int64(self.raw, v, sort).?, .ctx = self.raw };
    }
    pub fn mkReal(self: Context, num: i32, den: i32) Ast {
        return .{ .raw = z3.Z3_mk_real(self.raw, @intCast(num), @intCast(den)).?, .ctx = self.raw };
    }
    pub fn mkNumeral(self: Context, s: [:0]const u8, sort: Sort) Ast {
        return .{ .raw = z3.Z3_mk_numeral(self.raw, s, sort.raw).?, .ctx = self.raw };
    }

    // ---- Solver ----
    pub fn mkSolver(self: Context) Solver {
        const s = z3.Z3_mk_solver(self.raw).?;
        z3.Z3_solver_inc_ref(self.raw, s);
        return .{ .raw = s, .ctx = self.raw };
    }
    pub fn mkSolverForLogic(self: Context, logic: [:0]const u8) Solver {
        const sym = z3.Z3_mk_string_symbol(self.raw, logic).?;
        const s = z3.Z3_mk_solver_for_logic(self.raw, sym).?;
        z3.Z3_solver_inc_ref(self.raw, s);
        return .{ .raw = s, .ctx = self.raw };
    }
    // TODO: Add mk_simple_solver and mk_solver_from_tactic
    // right now we keep this simple

    // ---- Optimize ----
    pub fn mkOptimize(self: Context) Optimize {
        const o = z3.Z3_mk_optimize(self.raw).?;
        z3.Z3_optimize_inc_ref(self.raw, o);
        return .{ .raw = o, .ctx = self.raw };
    }

    // ---- Version check ----
    pub fn getVersion() struct { major: u32, minor: u32, build: u32, revision: u32 } {
        var major: c_uint = 0;
        var minor: c_uint = 0;
        var build: c_uint = 0;
        var revision: c_uint = 0;
        z3.Z3_get_version(&major, &minor, &build, &revision);
        return .{
            .major = @intCast(major),
            .minor = @intCast(minor),
            .build = @intCast(build),
            .revision = @intCast(revision),
        };
    }
};

// ---- Sort wrapper ----

pub const Sort = struct {
    raw: *z3.Z3_sort,
    ctx: *z3.Z3_context,

    pub fn toString(self: Sort) ?[*:0]const u8 {
        return z3.Z3_sort_to_string(self.ctx, self.raw);
    }
    pub fn kind(self: Sort) z3.Z3_sort_kind {
        return z3.Z3_get_sort_kind(self.ctx, self.raw);
    }
};

// ---- AST wrapper ----

pub const Ast = struct {
    raw: *z3.Z3_ast,
    ctx: *z3.Z3_context, // TODO: should be a const pointer, or not held at all

    pub fn toString(self: Ast) ?[*:0]const u8 {
        return z3.Z3_ast_to_string(self.ctx, self.raw);
    }

    pub fn eql(self: Ast, other: Ast) bool {
        return z3.Z3_is_eq_ast(self.ctx, self.raw, other.raw);
    }

    pub fn getSort(self: Ast) Sort {
        return .{ .raw = z3.Z3_get_sort(self.ctx, self.raw).?, .ctx = self.ctx };
    }

    // Boolean ops
    pub fn not(self: Ast) Ast {
        return .{ .raw = z3.Z3_mk_not(self.ctx, self.raw).?, .ctx = self.ctx };
    }
    pub fn @"and"(self: Ast, other: Ast) Ast {
        var args = [2]?*z3.Z3_ast{ self.raw, other.raw };
        return .{ .raw = z3.Z3_mk_and(self.ctx, 2, &args).?, .ctx = self.ctx };
    }
    // TODO factor out the pattern into a function called doMany
    pub fn ands(self: Ast, others: []const Ast) Ast {
        const alloc = std.heap.page_allocator;
        const ptrs = alloc.alloc(?*z3.Z3_ast, others.len + 1) catch unreachable;
        defer alloc.free(ptrs);
        ptrs[0] = self.raw;
        for (others, 1..) |a, i| ptrs[i] = a.raw;
        return .{
            .raw = z3.Z3_mk_and(self.ctx, @intCast(ptrs.len), ptrs.ptr).?,
            .ctx = self.ctx,
        };
    }

    pub fn ors(self: Ast, others: []const Ast) Ast {
        const alloc = std.heap.page_allocator;
        const ptrs = alloc.alloc(?*z3.Z3_ast, others.len + 1) catch unreachable;
        defer alloc.free(ptrs);
        ptrs[0] = self.raw;
        for (others, 1..) |a, i| ptrs[i] = a.raw;
        return .{
            .raw = z3.Z3_mk_or(self.ctx, @intCast(ptrs.len), ptrs.ptr).?,
            .ctx = self.ctx,
        };
    }
    pub fn @"or"(self: Ast, other: Ast) Ast {
        var args = [2]?*z3.Z3_ast{ self.raw, other.raw };
        return .{ .raw = z3.Z3_mk_or(self.ctx, 2, &args).?, .ctx = self.ctx };
    }
    pub fn implies(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_implies(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn iff(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_iff(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn xor(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_xor(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }

    // Arithmetic ops
    pub fn add(self: Ast, other: Ast) Ast {
        var args = [2]?*z3.Z3_ast{ self.raw, other.raw };
        return .{ .raw = z3.Z3_mk_add(self.ctx, 2, &args).?, .ctx = self.ctx };
    }
    pub fn adds(self: Ast, others: []const Ast) Ast {
        const alloc = std.heap.page_allocator;
        const ptrs = alloc.alloc(?*z3.Z3_ast, others.len + 1) catch unreachable;
        defer alloc.free(ptrs);
        ptrs[0] = self.raw;
        for (others, 1..) |a, i| ptrs[i] = a.raw;
        return .{ .raw = z3.Z3_mk_add(self.ctx, @intCast(ptrs.len), ptrs.ptr).?, .ctx = self.ctx };
    }
    pub fn sub(self: Ast, other: Ast) Ast {
        var args = [2]?*z3.Z3_ast{ self.raw, other.raw };
        return .{ .raw = z3.Z3_mk_sub(self.ctx, 2, &args).?, .ctx = self.ctx };
    }
    pub fn subs(self: Ast, others: []const Ast) Ast {
        const alloc = std.heap.page_allocator;
        const ptrs = alloc.alloc(?*z3.Z3_ast, others.len + 1) catch unreachable;
        defer alloc.free(ptrs);
        ptrs[0] = self.raw;
        for (others, 1..) |a, i| ptrs[i] = a.raw;
        return .{
            .raw = z3.Z3_mk_sub(self.ctx, @intCast(ptrs.len), ptrs.ptr).?,
            .ctx = self.ctx,
        };
    }
    pub fn mul(self: Ast, other: Ast) Ast {
        var args = [2]?*z3.Z3_ast{ self.raw, other.raw };
        return .{ .raw = z3.Z3_mk_mul(self.ctx, 2, &args).?, .ctx = self.ctx };
    }
    pub fn muls(self: Ast, others: []const Ast) Ast {
        const alloc = std.heap.page_allocator;
        const ptrs = alloc.alloc(?*z3.Z3_ast, others.len + 1) catch unreachable;
        defer alloc.free(ptrs);
        ptrs[0] = self.raw;
        for (others, 1..) |a, i| ptrs[i] = a.raw;
        return .{
            .raw = z3.Z3_mk_mul(self.ctx, @intCast(ptrs.len), ptrs.ptr).?,
            .ctx = self.ctx,
        };
    }
    pub fn div(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_div(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn mod(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_mod(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn neg(self: Ast) Ast {
        return .{ .raw = z3.Z3_mk_unary_minus(self.ctx, self.raw).?, .ctx = self.ctx };
    }
    pub fn lt(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_lt(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn le(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_le(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn gt(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_gt(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn ge(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_ge(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn eq(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_eq(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }

    // Bit-vector ops
    pub fn bvadd(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvadd(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn bvsub(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvsub(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn bvmul(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvmul(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn bvand(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvand(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn bvor(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvor(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn bvxor(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvxor(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn bvnot(self: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvnot(self.ctx, self.raw).?, .ctx = self.ctx };
    }
    pub fn bvneg(self: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvneg(self.ctx, self.raw).?, .ctx = self.ctx };
    }
    pub fn bvshl(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvshl(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn bvlshr(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvlshr(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn bvashr(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvashr(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn bvult(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvult(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn bvslt(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_bvslt(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }
    pub fn extract(self: Ast, high: u32, low: u32) Ast {
        return .{ .raw = z3.Z3_mk_extract(self.ctx, @intCast(high), @intCast(low), self.raw).?, .ctx = self.ctx };
    }
    pub fn concat(self: Ast, other: Ast) Ast {
        return .{ .raw = z3.Z3_mk_concat(self.ctx, self.raw, other.raw).?, .ctx = self.ctx };
    }

    // Array ops
    pub fn select(self: Ast, idx: Ast) Ast {
        return .{ .raw = z3.Z3_mk_select(self.ctx, self.raw, idx.raw).?, .ctx = self.ctx };
    }
    pub fn store(self: Ast, idx: Ast, val: Ast) Ast {
        return .{ .raw = z3.Z3_mk_store(self.ctx, self.raw, idx.raw, val.raw).?, .ctx = self.ctx };
    }

    // Simplify
    pub fn simplify(self: Ast) Ast {
        return .{ .raw = z3.Z3_simplify(self.ctx, self.raw).?, .ctx = self.ctx };
    }
};

// ---- Model wrapper ----

pub const Model = struct {
    raw: *z3.Z3_model,
    ctx: *z3.Z3_context,

    pub fn deinit(self: Model) void {
        z3.Z3_model_dec_ref(self.ctx, self.raw);
    }

    pub fn toString(self: Model) ?[*:0]const u8 {
        return z3.Z3_model_to_string(self.ctx, self.raw);
    }

    /// Evaluate an expression in the model. Returns null if evaluation fails.
    pub fn eval(self: Model, expr: Ast, completion: bool) ?Ast {
        var result: ?*z3.Z3_ast = null;
        if (z3.Z3_model_eval(self.ctx, self.raw, expr.raw, completion, &result)) {
            return .{ .raw = result.?, .ctx = self.ctx };
        }
        return null;
    }

    pub fn numConsts(self: Model) u32 {
        return @intCast(z3.Z3_model_get_num_consts(self.ctx, self.raw));
    }
    pub fn numFuncs(self: Model) u32 {
        return @intCast(z3.Z3_model_get_num_funcs(self.ctx, self.raw));
    }
};

// ---- Solver wrapper ----

pub const CheckResult = enum {
    sat,
    unsat,
    unknown,
};

pub const Solver = struct {
    raw: *z3.Z3_solver,
    ctx: *z3.Z3_context,

    pub fn deinit(self: Solver) void {
        z3.Z3_solver_dec_ref(self.ctx, self.raw);
    }

    pub fn assert(self: Solver, expr: Ast) void {
        z3.Z3_solver_assert(self.ctx, self.raw, expr.raw);
    }

    pub fn push(self: Solver) void {
        z3.Z3_solver_push(self.ctx, self.raw);
    }

    pub fn pop(self: Solver, n: u32) void {
        z3.Z3_solver_pop(self.ctx, self.raw, @intCast(n));
    }

    pub fn reset(self: Solver) void {
        z3.Z3_solver_reset(self.ctx, self.raw);
    }

    pub fn check(self: Solver) CheckResult {
        return switch (z3.Z3_solver_check(self.ctx, self.raw)) {
            .L_TRUE => .sat,
            .L_FALSE => .unsat,
            .L_UNDEF => .unknown,
        };
    }

    pub fn checkAssumptions(self: Solver, assumptions: []const Ast) CheckResult {
        const ptrs = std.heap.page_allocator.alloc(?*z3.Z3_ast, assumptions.len) catch return .unknown;
        defer std.heap.page_allocator.free(ptrs);
        for (assumptions, 0..) |a, i| ptrs[i] = a.raw;
        return switch (z3.Z3_solver_check_assumptions(self.ctx, self.raw, @intCast(ptrs.len), ptrs.ptr)) {
            .L_TRUE => .sat,
            .L_FALSE => .unsat,
            .L_UNDEF => .unknown,
        };
    }

    pub fn getModel(self: Solver) ?Model {
        const m = z3.Z3_solver_get_model(self.ctx, self.raw) orelse return null;
        z3.Z3_model_inc_ref(self.ctx, m);
        return .{ .raw = m, .ctx = self.ctx };
    }

    pub fn getUnsatCore(self: Solver) AstVector {
        const v = z3.Z3_solver_get_unsat_core(self.ctx, self.raw).?;
        z3.Z3_ast_vector_inc_ref(self.ctx, v);
        return .{ .raw = v, .ctx = self.ctx };
    }

    pub fn getReasonUnknown(self: Solver) ?[*:0]const u8 {
        return z3.Z3_solver_get_reason_unknown(self.ctx, self.raw);
    }

    pub fn toString(self: Solver) ?[*:0]const u8 {
        return z3.Z3_solver_to_string(self.ctx, self.raw);
    }

    pub fn numScopes(self: Solver) u32 {
        return @intCast(z3.Z3_solver_get_num_scopes(self.ctx, self.raw));
    }
};

// ---- Optimize wrapper ----

pub const Optimize = struct {
    raw: *z3.Z3_optimize,
    ctx: *z3.Z3_context,

    pub fn deinit(self: Optimize) void {
        z3.Z3_optimize_dec_ref(self.ctx, self.raw);
    }

    pub fn assert(self: Optimize, expr: Ast) void {
        z3.Z3_optimize_assert(self.ctx, self.raw, expr.raw);
    }

    pub fn maximize(self: Optimize, expr: Ast) u32 {
        return @intCast(z3.Z3_optimize_maximize(self.ctx, self.raw, expr.raw));
    }

    pub fn minimize(self: Optimize, expr: Ast) u32 {
        return @intCast(z3.Z3_optimize_minimize(self.ctx, self.raw, expr.raw));
    }

    pub fn check(self: Optimize) CheckResult {
        return switch (z3.Z3_optimize_check(self.ctx, self.raw, 0, undefined)) {
            .L_TRUE => .sat,
            .L_FALSE => .unsat,
            .L_UNDEF => .unknown,
        };
    }

    pub fn getModel(self: Optimize) ?Model {
        const m = z3.Z3_optimize_get_model(self.ctx, self.raw) orelse return null;
        z3.Z3_model_inc_ref(self.ctx, m);
        return .{ .raw = m, .ctx = self.ctx };
    }

    pub fn getLower(self: Optimize, idx: u32) Ast {
        return .{ .raw = z3.Z3_optimize_get_lower(self.ctx, self.raw, @intCast(idx)).?, .ctx = self.ctx };
    }

    pub fn getUpper(self: Optimize, idx: u32) Ast {
        return .{ .raw = z3.Z3_optimize_get_upper(self.ctx, self.raw, @intCast(idx)).?, .ctx = self.ctx };
    }

    pub fn toString(self: Optimize) ?[*:0]const u8 {
        return z3.Z3_optimize_to_string(self.ctx, self.raw);
    }
};

// ---- AstVector wrapper ----

pub const AstVector = struct {
    raw: *z3.Z3_ast_vector,
    ctx: *z3.Z3_context,

    pub fn deinit(self: AstVector) void {
        z3.Z3_ast_vector_dec_ref(self.ctx, self.raw);
    }

    pub fn size(self: AstVector) u32 {
        return @intCast(z3.Z3_ast_vector_size(self.ctx, self.raw));
    }

    pub fn get(self: AstVector, i: u32) Ast {
        return .{ .raw = z3.Z3_ast_vector_get(self.ctx, self.raw, @intCast(i)).?, .ctx = self.ctx };
    }

    pub fn push(self: AstVector, a: Ast) void {
        z3.Z3_ast_vector_push(self.ctx, self.raw, a.raw);
    }

    pub fn toString(self: AstVector) ?[*:0]const u8 {
        return z3.Z3_ast_vector_to_string(self.ctx, self.raw);
    }
};
